/*
 * forum
 *
 * Тестовое задание для реализации проекта \"Форумы\" на курсе по базам данных в Технопарке Mail.ru (https://park.mail.ru).
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	router2 "go-server-server-generated/go/router"
	"log"
	"net/http"
)

func main() {
	log.Printf("Server started")

	router := router2.NewRouter()

	log.Println(http.ListenAndServe(":5000", router))
}
